[package]
name = "geo_converter"
version = "0.1.0"
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
rust_decimal = "1.15.0"
rust_decimal_macros = "1.15.0"
